const LOGIN_KEYS={config:"soraya_config",name:"soraya_person_name"};
let loginClient=null;
function el(id){return document.getElementById(id)}
function setLoginStatus(message,type=""){const n=el("loginStatus");if(!n)return;n.classList.remove("ok","bad");if(type)n.classList.add(type);n.textContent=message}
function readLoginConfig(){try{const raw=localStorage.getItem(LOGIN_KEYS.config);return raw?JSON.parse(raw):null}catch(e){return null}}
function fillConfigForm(c){if(!c)return;el("loginSupabaseUrl").value=c.supabaseUrl||"";el("loginSupabaseAnonKey").value=c.supabaseAnonKey||"";el("loginEngineUrl").value=c.engineUrl||""}
function initLoginClient(c){if(!window.supabase)throw new Error("Supabase CDN wurde nicht geladen.");if(!c||!c.supabaseUrl||!c.supabaseAnonKey)throw new Error("Supabase-Verbindung fehlt.");loginClient=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true}});return loginClient}
function getLoginClient(){return loginClient||initLoginClient(readLoginConfig())}
async function checkLoginSession(){try{const client=getLoginClient();const{data,error}=await client.auth.getSession();if(error)throw error;if(data&&data.session&&data.session.user){const email=data.session.user.email||"";if(email&&!localStorage.getItem(LOGIN_KEYS.name))localStorage.setItem(LOGIN_KEYS.name,email.split("@")[0]);setLoginStatus("✅ Du bist bereits eingeloggt. Du kannst zur App zurück.","ok");return true}setLoginStatus("Bereit zum Einloggen.");return false}catch(e){const box=el("connectionBox");if(box)box.open=true;setLoginStatus("Bitte Verbindung einrichten oder in der App unter Verbindung speichern.","bad");return false}}
async function signIn(){try{const email=el("loginEmail").value.trim(),password=el("loginPassword").value;if(!email||!password){setLoginStatus("Bitte E-Mail und Passwort ausfüllen.","bad");return}setLoginStatus("Login läuft ...");const client=getLoginClient();const{data,error}=await client.auth.signInWithPassword({email,password});if(error)throw error;const userEmail=data&&data.user&&data.user.email?data.user.email:email;localStorage.setItem(LOGIN_KEYS.name,localStorage.getItem(LOGIN_KEYS.name)||userEmail.split("@")[0]);setLoginStatus("✅ Login erfolgreich. Soraya öffnet die App ...","ok");setTimeout(()=>{window.location.href="/"},650)}catch(e){setLoginStatus("Login fehlgeschlagen: "+(e.message||String(e)),"bad")}}
async function signUp(){try{const email=el("loginEmail").value.trim(),password=el("loginPassword").value;if(!email||!password){setLoginStatus("Bitte E-Mail und Passwort ausfüllen.","bad");return}setLoginStatus("Registrierung läuft ...");const client=getLoginClient();const{error}=await client.auth.signUp({email,password});if(error)throw error;setLoginStatus("✅ Registrierung gestartet. Bitte E-Mail bestätigen, falls Supabase das verlangt.","ok")}catch(e){setLoginStatus("Registrierung fehlgeschlagen: "+(e.message||String(e)),"bad")}}
function saveConfig(){try{const c={supabaseUrl:el("loginSupabaseUrl").value.trim(),supabaseAnonKey:el("loginSupabaseAnonKey").value.trim(),engineUrl:el("loginEngineUrl").value.trim().replace(/\/$/,"")};if(!c.supabaseUrl||!c.supabaseAnonKey||!c.engineUrl){setLoginStatus("Bitte alle Verbindungsfelder ausfüllen.","bad");return}localStorage.setItem(LOGIN_KEYS.config,JSON.stringify(c));loginClient=null;initLoginClient(c);setLoginStatus("✅ Verbindung gespeichert. Du kannst dich jetzt einloggen.","ok")}catch(e){setLoginStatus("Verbindung konnte nicht gespeichert werden: "+(e.message||String(e)),"bad")}}
document.addEventListener("DOMContentLoaded",()=>{const c=readLoginConfig();fillConfigForm(c);if(!c){const box=el("connectionBox");if(box)box.open=true;setLoginStatus("Noch keine Verbindung gespeichert. Bitte einmal Verbindung einrichten.","bad")}else checkLoginSession();const form=el("loginForm");if(form)form.addEventListener("submit",ev=>{ev.preventDefault();signIn()})});
window.sorayaLogin={signIn,signUp,saveConfig,checkLoginSession};
